apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.labels.app }}-deployment
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.replicacount }}
  selector:
    matchLabels:
      name: {{ .Values.labels.app }}
  template:
    metadata:
      name: {{ .Values.labels.app }}
    spec:
      containers:
        - name: {{ .Values.labels.app }}
          image: {{ .Values.containers.image }}
          ports:
            - containerPort: {{ .Values.containers.port }}
              protocol: TCP
      imagePullSecrets:
        - name: ecr-cred
