apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.labels.app }}-deployment
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}-app
  template:
    metadata:
      name: {{ .Values.labels.app }}
      labels:
        app: {{ .Values.labels.app }}-app
    spec:
      containers:
        - name: {{ .Values.labels.app }}
          image: "{{ .Values.containers.image }}:{{ .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.containers.port }}
              protocol: TCP
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.containers.port }}
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.containers.port }}
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
      imagePullSecrets:
        - name: ecr-cred