apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.labels.app }}-deployment
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.replicacount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}-app
  template:
    metadata:
      name: {{ .Values.labels.app }}
      labels:
        app: {{ .Values.labels.app }}-app
    spec:
      containers:
        - name: {{ .Values.labels.app }}
          image: "{{ .Values.containers.image }}:{{ .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.containers.port }}
              protocol: TCP
      imagePullSecrets:
        - name: ecr-cred