apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labels.app }}-service
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    name: {{ .Values.labels.app }}
  type: NodePort
  ports:
    - port: {{ .Values.containers.port }}
      protocol: TCP
      nodePort: 30002
