apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labels.app }}-service
  namespace: eos-dev
spec:
  selector:
    name: {{ .Values.labels.app }}
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 30002
