replicaCount: 1

metadata:
  namespace: eos-dev

containers:
  image: 134448505602.dkr.ecr.ap-south-1.amazonaws.com/dev/eos-micro-services-admin
  port: 8090

resources:
  requests:
    cpu: 125m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi

labels:
  app: eos-micro-services-admin
